### PR TITLE
Feature select language

### PR DESCRIPTION
**Pull request by Surkhojb**
## :scroll: Description

Related to issue https://github.com/alisonthemonster/Presently/issues/99:
 - Implemented new settings option to change the language without the need to restart 
the whole application.
 - I created a LocationHelper to update the language in a different way depending of API version. 
- Implemented override attachBaseContext at ContainerActivity to load the last language saved from Settings Fragment.

**IMPORTANT: With the first changes at SettingsFragment and just with the use of attachBaseContext at ContainerActivity the language changes correctly but I noticed a bad behaviour at EntryViewModel here:**

`` private val inspiration = application.resources.getStringArray(R.array.inspirations).random() ``
``private val promptsArray = application.resources.getStringArray(R.array.prompts)``
``getApplication<Application>().resources``

**Locale value using ``application.resources`` is always the mobile phone language, so no matter what language you selected previously at settings it always will take the mobile phone language. To show the correct language at ViewModel strings I just created a BindingAdapter class to handle locale change and update the UI with the correct value by locale

, e.g:**

`` @BindingAdapter("hintSupportingLocale")``
  `` fun updateHint(view: EditText,text: String?) {``
        ``val prompt = view.resources?.getStringArray(R.array.prompts)?.random() ?: ""``
        ``view.setHint(prompt)``
``} ``

## :green_heart: How did you test it?

Texted manually with an emulator.

## :camera_flash: Screenshots / GIFs

image
image
image
image
image
image

### CODE REVIEW

**Comment by alisonthemonster** [comment]
This is great thank you so much for working on this!

You've pointed out a sticky issue with the resources from the application context. I'm working on a refactor to remove that so we don't have to use all these binding adapters. Stay tuned and thank you again!

**Comment by Surkhojb** [comment]
@alisonthemonster I am not very happy about the binding adapter approach but I couldn't be able to update the ViewModel with the last selected locale. I can't wait to see how you solve it!!.

If you don't mind I would like to keep working on the project.

Happy coding!

**Comment by alisonthemonster** [comment]
Yes please keep working on the project! I want to move this fragment away from data binding so we don't have this issue, but I'm also thinking this may be a good case for rewriting in an MVI way like with Mavericks. We'll see how much time I get on my hands 😆 

Also I already noticed a few existing translation bugs thanks to this feature so thank you very very much!

**Comment by alisonthemonster** [comment]
Also the CI is failing because an espresso test checks the value of the hint and now you're using a data binding expression to set it. We'll hopefully find another way around this :)

**Comment by alisonthemonster** [comment]
Okay I rewrote the entry screen with Mavericks and now there are no usages of application resources!

I rebased this branch, added analytics, removed the binding adapters, updated the settings icon, fixed some translation issues, and added support for Brazilian Portuguese. Let me see if I can get those changes into this pull request, might have to create a new PR

**Comment by alisonthemonster** [comment]
That worked! Going to merge this PR and get another one opened up to create the next release version 🥳 will ship it soon :) thank you so much for getting this done and for pushing me to modernize some components!

**Pull request merged**
