### PR TITLE
Updated Screenshots in the README file

### PR DESCRIPTION
**Pull request by yadunandanbhat**
## :scroll: Description

Added some updated screenshots in the readme file, because the old ones were outdated.

### CODE REVIEW

**Comment by alisonthemonster** [comment]
Thanks for updating the screenshots! Looks like a bunch of build files got added here, would you mind removing those? Only the Readme should be changed. Thank you!

**Comment by yadunandanbhat** [comment]
Okay will do!

**Comment by yadunandanbhat** [comment]
I have removed the build files. Can you check?

**Comment by alisonthemonster** [comment]
Closing since this work was recently completed.

**Pull request closed without merging**
